version: '2.3'

services:
  face_recognition:
    image: face_recognition
    container_name: face_recognition
    working_dir: /face_recognition/
    build:
      context: .
      #Uncomment this line to run the example on the GPU (requires Nvidia-Docker)
      # dockerfile: Dockerfile.gpu 
    command: python3 -u main.py
    volumes:
      - ./:/face_recognition
      - ../muskia/uploads:/uploads
    #Uncomment this line to run the example on the GPU (requires Nvidia-Docker)
    # runtime: nvidia

  image-uploader:
    build:
      context: ../muskia
      dockerfile: Dockerfile
    image:
      muskia:latest
    ports:
      - "5002:5002"
    environment:
      HOST: 0.0.0.0
    depends_on:
      - face_recognition
    volumes:
      - ../muskia/uploads:/uploads



